spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/countries_dev
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

cache:
  config:
    entryTtl: 60
    countryNames:
      entryTtl: 30


